services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: MovieTheater
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cinema-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d MovieTheater"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: cinema-booking:latest
    container_name: cinema_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/MovieTheater
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    networks:
      - cinema-net

volumes:
  postgres_data:

networks:
  cinema-net:
